version: '3'

services:
  challenge:
    image: python:3.7
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: "8000"
        HOST: "mongodb://mongodb:27017"
        DB: "tictactoe"
        DEBUG: "True"
    ports:
    - "8000:8000"
    restart: on-failure
    links:
      - mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null
